name: C++ CI with GoogleTest + SonarQube Cloud

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-test-sonar:
    runs-on: [self-hosted, linux]

    defaults:
      run:
        shell: bash
        working-directory: ./project

    env:
      BUILD_WRAPPER_OUT_DIR: bw-output
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install gcovr
        run: pip install gcovr

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v7

      - name: Configure
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_FLAGS="--coverage -O0 -g"
          -DCMAKE_CXX_FLAGS="--coverage -O0 -g"

      - name: Build with Build Wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir "${BUILD_WRAPPER_OUT_DIR}" \
          cmake --build build --clean-first

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Generate coverage report
        run: gcovr --root . --sonarqube coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: project
          args: >
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.cfamily.compile-commands=bw-output/compile_commands.json
            -Dsonar.coverageReportPaths=coverage.xml
            -Dsonar.qualitygate.wait=true